# NumPy

In [1]:
import numpy as np

### DataTypes & Attributes

### ndarray

In [28]:
array1 = np.array([1, 2, 3])
array1

array([1, 2, 3])

In [4]:
type(array1)

numpy.ndarray

In [30]:
array2 = np.array([
    [1, 2.0, 3.3],
    [4, 5, 6.5]
])


array3 = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])

In [31]:
array2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [32]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
array1.shape

(3,)

In [12]:
array2.shape

(2, 3)

In [13]:
array3.shape

(2, 3, 3)

In [14]:
array1.ndim, array2.ndim, array3.ndim

(1, 2, 3)

In [15]:
array1.dtype, array2.dtype, array3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [ ]:
# change int32 to int64
# int64_array = int32_array.astype(np.int64)

In [16]:
array1.size, array2.size, array3.size

(3, 6, 18)

In [17]:
type(array1), type(array2), type(array3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a Dataframe from a NumPy Array

In [18]:
import pandas as pd

df = pd.DataFrame(array2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [19]:
array2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

## Create numpy arrays

### ones

In [20]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

### zeros

In [22]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

### range

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

### random

In [26]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[0, 2, 6, 3, 0],
       [7, 8, 1, 9, 4],
       [7, 3, 9, 8, 7]])

In [31]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.52979061, 0.06286338, 0.47574407],
       [0.32244747, 0.24725838, 0.66014404],
       [0.9116609 , 0.75654222, 0.6937285 ],
       [0.69673596, 0.40342351, 0.43184045],
       [0.1683256 , 0.05092538, 0.67555594]])

In [32]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.47516053, 0.01111055, 0.02894428],
       [0.54968695, 0.37608986, 0.13536572],
       [0.18351484, 0.19470797, 0.23839749],
       [0.49226761, 0.03726901, 0.50099588],
       [0.56168218, 0.0165908 , 0.50065798]])

### Pseudo-random numbers

In [33]:
np.random.seed()

## Numpy Seed

In [1]:
import numpy as np
np.random.seed()

In [3]:
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[3, 3, 2],
       [0, 4, 1],
       [5, 7, 6],
       [7, 8, 5],
       [1, 2, 6]])

Generate random numbers that reproducable.
- For any computer that has the notebook

In [6]:
np.random.seed(seed=0)
random_array_5 = np.random.randint(10, size=(5, 3))
random_array_5

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [12]:
np.random.seed(7)
random_array_6 = np.random.random((5, 3))
random_array_6

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

What seed does is:
- It reproduce the same random number everytime
- This allows us to reproduce the random numbers in any computer

# Change DataType

In [23]:
ar1 = np.array([2, 3], dtype='int64')
ar1.dtype

dtype('int64')

In [25]:
ar1 = ar1.astype(dtype='int32')
ar1.dtype

dtype('int32')

## Viewing Arrays and Matrices

In [26]:
# Take the unique or distinct number in the array
np.unique(random_array_5)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# Get the first row
array1[0]

1

In [35]:
array2[0]

array([1. , 2. , 3.3])

In [37]:
array3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
array3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [53]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 5, 3, 0, 5],
         [7, 1, 8, 4, 9],
         [0, 2, 0, 7, 6],
         [2, 9, 9, 5, 1]],

        [[0, 0, 9, 1, 1],
         [5, 3, 2, 0, 4],
         [8, 7, 1, 4, 9],
         [3, 6, 7, 1, 0]],

        [[2, 7, 0, 0, 9],
         [8, 2, 0, 5, 5],
         [0, 9, 0, 8, 4],
         [5, 1, 4, 0, 7]]],


       [[[2, 0, 3, 9, 8],
         [3, 7, 1, 0, 1],
         [4, 6, 1, 0, 1],
         [0, 1, 8, 4, 1]],

        [[6, 8, 5, 2, 4],
         [7, 4, 1, 2, 8],
         [5, 2, 9, 6, 2],
         [5, 7, 7, 5, 5]],

        [[6, 0, 6, 4, 6],
         [2, 6, 8, 7, 0],
         [5, 8, 9, 7, 7],
         [6, 2, 5, 6, 1]]]])

In [54]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [56]:
# get the first 1 numbers of the inner most array
a4[:, :, :, :1]

array([[[[0],
         [7],
         [0],
         [2]],

        [[0],
         [5],
         [8],
         [3]],

        [[2],
         [8],
         [0],
         [5]]],


       [[[2],
         [3],
         [4],
         [0]],

        [[6],
         [7],
         [5],
         [5]],

        [[6],
         [2],
         [5],
         [6]]]])

## Manipulating & Comparing Arrays

### Arithmetics

In [57]:
array1

array([1, 2, 3])

In [58]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [61]:
array1 + ones

array([2., 3., 4.])

In [62]:
array1*array2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [64]:
array2*array3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [65]:
np.square(array2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [66]:
np.add(array1, ones)

array([2., 3., 4.])

In [68]:
np.mod(array2, 2)

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [69]:
np.exp(array1) # array**e

array([ 2.71828183,  7.3890561 , 20.08553692])

In [72]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229])

In [73]:
np.log(np.exp(array1)) # perform log to return array**e to its original

array([1., 2., 3.])