# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [19]:
# Create a 1-dimensional NumPy array using np.array()
ar1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
ar2 = np.array([[1, 2, 3],
              [4, 5, 6]])
# Create a 3-dimensional Numpy array using np.array()
ar3 = np.array([[[1,2,3]],
              [[4,5,6]],
              [[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [25]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(
    f"shape: {ar1.shape}\n",
    f"dimension: {ar1.ndim}\n",
    f"datatype: {ar1.dtype}\n",
    f"size: {ar1.size}\n",
    f"type: {type(ar1)}\n"
     )

shape: (3,)
 dimension: 1
 datatype: int32
 size: 3
 type: <class 'numpy.ndarray'>



In [26]:
# Attributes of 2-dimensional array
print(
    f"shape: {ar2.shape}\n",
    f"dimension: {ar2.ndim}\n",
    f"datatype: {ar2.dtype}\n",
    f"size: {ar2.size}\n",
    f"type: {type(ar2)}\n"
     )

shape: (2, 3)
 dimension: 2
 datatype: int32
 size: 6
 type: <class 'numpy.ndarray'>



In [27]:
# Attributes of 3-dimensional array
print(
    f"shape: {ar3.shape}\n",
    f"dimension: {ar3.ndim}\n",
    f"datatype: {ar3.dtype}\n",
    f"size: {ar3.size}\n",
    f"type: {type(ar3)}\n"
     )

shape: (3, 1, 3)
 dimension: 3
 datatype: int32
 size: 9
 type: <class 'numpy.ndarray'>



In [30]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
pd.DataFrame(ar2)

0  1  2
0  1  2  3
1  4  5  6

In [36]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0, 100, 3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [39]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_ten = np.random.randint(10, size=(7,2))
arr_ten

array([[1, 4],
       [2, 2],
       [6, 5],
       [5, 6],
       [4, 8],
       [9, 1],
       [5, 3]])

In [40]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_arr = np.random.random((3, 5))
float_arr

array([[0.08549649, 0.62366541, 0.73755786, 0.29907019, 0.61780932],
       [0.1158061 , 0.30214301, 0.32939066, 0.80662057, 0.46413732],
       [0.92729062, 0.50355597, 0.21430859, 0.68446077, 0.09364356]])

In [42]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
seed_arr = np.random.randint(10, size=(4, 6))
seed_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

Ans: Same result, bcs of the random seed set to 42

In [4]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
var_arr = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(var_arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
var_arr

array([[5, 5, 6, 7, 3, 7, 4],
       [1, 4, 6, 5, 4, 8, 6],
       [8, 2, 9, 9, 5, 8, 6]])

In [6]:
# Find the 0'th index of the latest array you created
var_arr[0]

array([5, 5, 6, 7, 3, 7, 4])

In [7]:
# Get the first 2 rows of latest array you created
var_arr[:2]

array([[5, 5, 6, 7, 3, 7, 4],
       [1, 4, 6, 5, 4, 8, 6]])

In [10]:
# Get the first 2 values of the first 2 rows of the latest array
var_arr[:2, :2]

array([[5, 5],
       [1, 4]])

In [14]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ran_arr = np.random.randint(10, size=(3, 5))
ones_arr = np.ones((3, 5))
ran_arr, ones_arr

(array([[5, 1, 3, 8, 7],
        [0, 3, 3, 0, 1],
        [6, 7, 1, 9, 3]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [15]:
# Add the two arrays together
ran_arr + ones_arr

array([[ 6.,  2.,  4.,  9.,  8.],
       [ 1.,  4.,  4.,  1.,  2.],
       [ 7.,  8.,  2., 10.,  4.]])

In [16]:
# Create another array of ones of shape (5, 3)
ones_arr1 = np.ones((5, 3))
ones_arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# Try add the array of ones and the other most recent array together
ran_arr + ones_arr1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [18]:
# Create another array of ones of shape (3, 5)
# Instead, we can use Transpose
ran_arr + ones_arr1.T

array([[ 6.,  2.,  4.,  9.,  8.],
       [ 1.,  4.,  4.,  1.,  2.],
       [ 7.,  8.,  2., 10.,  4.]])

In [19]:
# Subtract the new array of ones from the other most recent array
ran_arr - ones_arr

array([[ 4.,  0.,  2.,  7.,  6.],
       [-1.,  2.,  2., -1.,  0.],
       [ 5.,  6.,  0.,  8.,  2.]])

In [20]:
# Multiply the ones array with the latest array
ran_arr * ones_arr

array([[5., 1., 3., 8., 7.],
       [0., 3., 3., 0., 1.],
       [6., 7., 1., 9., 3.]])

In [21]:
# Take the latest array to the power of 2 using '**'
ran_arr**2

array([[25,  1,  9, 64, 49],
       [ 0,  9,  9,  0,  1],
       [36, 49,  1, 81,  9]])

In [22]:
# Do the same thing with np.square()
np.square(ran_arr)

array([[25,  1,  9, 64, 49],
       [ 0,  9,  9,  0,  1],
       [36, 49,  1, 81,  9]])

In [23]:
# Find the mean of the latest array using np.mean()
np.mean(ran_arr)

3.8

In [24]:
# Find the maximum of the latest array using np.max()
np.max(ran_arr)

9

In [25]:
# Find the minimum of the latest array using np.min()
np.min(ran_arr)

0

In [26]:
# Find the standard deviation of the latest array
np.std(ran_arr)

2.9028721409436327

In [27]:
# Find the variance of the latest array
np.var(ran_arr)

8.42666666666667

In [28]:
# Check std and var
np.sqrt(np.var(ran_arr))

2.9028721409436327

In [32]:
# Reshape the latest array to (3, 5, 1)
reshape_ran_arr = ran_arr.reshape(3, 5, 1)
reshape_ran_arr

array([[[5],
        [1],
        [3],
        [8],
        [7]],

       [[0],
        [3],
        [3],
        [0],
        [1]],

       [[6],
        [7],
        [1],
        [9],
        [3]]])

In [33]:
# Transpose the latest array
reshape_ran_arr.T

array([[[5, 0, 6],
        [1, 3, 7],
        [3, 3, 1],
        [8, 0, 9],
        [7, 1, 3]]])

What does the transpose do?

In [34]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
x_arr = np.random.randint(10, size=(3, 3))
y_arr = np.random.randint(10, size=(3, 2))

x_arr.shape, y_arr.shape

((3, 3), (3, 2))

In [43]:
x_arr

array([[6, 4, 5],
       [3, 6, 2],
       [2, 2, 7]])

In [44]:
y_arr

array([[1, 9],
       [8, 3],
       [4, 9]])

In [35]:
# Perform a dot product on the two newest arrays you created
x_arr.dot(y_arr)

array([[ 58, 111],
       [ 59,  63],
       [ 46,  87]])

In [45]:
# or
np.dot(x_arr, y_arr)

array([[ 58, 111],
       [ 59,  63],
       [ 46,  87]])

In [40]:
y_arr.dot(x_arr)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [42]:
y_arr.T.dot(x_arr)

array([[ 38,  60,  49],
       [ 81,  72, 114]])

In [46]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
s_arr = np.random.randint(10, size=(4, 3))
t_arr = np.random.randint(10, size=(4, 3))

In [47]:
# Perform a dot product on the two newest arrays you created
np.dot(s_arr, t_arr)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [48]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(s_arr.T, t_arr)

array([[ 14,  12,  66],
       [ 52, 123, 155],
       [  6,  10,  25]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [49]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
o_arr = np.random.randint(10, size=(4, 2))
p_arr = np.random.randint(10, size=(4, 2))

In [50]:
# Compare the two arrays with '>'
o_arr > p_arr

array([[ True, False],
       [False,  True],
       [False,  True],
       [ True, False]])

What happens when you compare the arrays with `>`?

In [51]:
# Compare the two arrays with '>='
o_arr >= p_arr

array([[ True, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [52]:
# Find which elements of the first array are greater than 7
o_arr> 7, p_arr > 7

(array([[ True, False],
        [False,  True],
        [False,  True],
        [False, False]]),
 array([[False, False],
        [False, False],
        [False, False],
        [False, False]]))

In [53]:
# Which parts of each array are equal? (try using '==')
o_arr == p_arr

array([[False, False],
       [False, False],
       [ True, False],
       [False,  True]])

In [54]:
# Sort one of the arrays you just created in ascending order
np.sort(o_arr)

array([[3, 8],
       [3, 8],
       [2, 8],
       [6, 7]])

In [55]:
o_arr

array([[8, 3],
       [3, 8],
       [2, 8],
       [6, 7]])

In [56]:
# Sort the indexes of one of the arrays you just created
np.argsort(o_arr)

array([[1, 0],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int64)

In [58]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(o_arr)

0

In [70]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(o_arr)

4

In [71]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(o_arr, axis=1)

array([0, 1, 1, 1], dtype=int64)

In [73]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(o_arr, axis=0)

array([2, 0], dtype=int64)

In [75]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.70010272, -0.31919663,  2.9008263 ,  0.83663856, -1.7738385 ],
       [ 0.1305129 ,  1.23407507,  0.05024832,  0.5459805 , -0.4285107 ],
       [-0.24020483,  0.60534033, -0.83664128, -1.18925205, -0.64033373]])

In [77]:
# Create an array with 10 evenly spaced numbers between 1 and 100
lin_arr = np.linspace(1, 100, 10)
lin_arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.